train:
    datapath: "Dataset/DAVIS/JPEGImages/480p"
    valid_datapath: "Dataset/Simu_test/gray/256"
    maskpath: "Dataset/Masks/new/rand_cr24.mat"
    seed: 1
    patch_size: 128
    batch_size: 8
    ckpt_size: 10
    epochs: 100
    lr: 0.001

model:
    name: "RT"
    tag: "锁MaskCR8"
    color: 1
    width: 64
    temb_channel: 32
    num_blocks: [2,2,2]
    width_ratio: 3
    losstype: "RMSE"
    Mask_guide: "Mask"
    Temb_guide: False
    shortcut: "weight"
    blocktype: "rt"

flex:
    cr_train: [8]
    cr_model: 8
    cr_skip: 1
