train:
    datapath: "Dataset/DAVIS/JPEGImages/480p"
    valid_datapath: "Dataset/Simu_test/gray/256"
    seed: 1
    patch_size: 128
    batch_size: 16
    ckpt_size: 10
    epochs: 100
    lr: 0.001
    xformer: False
    gradient_checkpointing: False

model:
    name: "CT_U"
    color: 1
    losstype: "RMSE"
    down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D"]
    up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"]
    block_out_channels: [64, 128, 256]
    attention_head_dim: 8
    freq_shift: 0
    flip_sin_to_cos: True

flex:
    cr_train: [8]
    cr_model: 8
    cr_skip: 1
